name 'install_ruby'
maintainer 'The Authors'
maintainer_email 'you@example.com'
license 'all_rights'
description 'Installs/Configures install_ruby'
long_description 'Installs/Configures install_ruby'
version '0.1.0'

depends 'yum'
depends 'apt'
